name: ReRecipeCreators
version: 1.6
author: Kamesuta
description: Recipe Creator plugin
main: net.teamfruit.rerecipecreators.ReRecipeCreators
commands:
    recipe:
        description: Control over system Recipes
        usage: /recipe add | remove | info | lookup | help | reset | reload | permissions
permissions:
    rerecipecreators.add.shaped:
        default: op
        description: creates a shaped recipe
    rerecipecreators.add.shapeless:
        default: op
        description: creates a shapeless recipe
    rerecipecreators.info:
        default: op
        description: retrieves a recipes information
    rerecipecreators.lookup:
        default: op
        description: retrieves an items recipe ids
    rerecipecreators.remove:
        default: op
        description: removes a recipe
    rerecipecreators.reload:
        default: op
        description: reloads the recipes
    rerecipecreators.recipes.*:
        default: op
        description: gives player access to all recipes
    rerecipecreators.permissioncontrol:
        default: op
        description: gives a player access to permission managment
